name: Find My Local Pollie
version: "0.1.0"
slug: find_my_local_pollie
description: Find local political representatives from Home Assistant
url: https://github.com/you209/Find-My-Local-Pollie
arch:
  - amd64
  - aarch64
startup: application
boot: manual
init: false
webui: "http://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3001
ports_description:
  3000/tcp: Web interface
map:
  - type: data
    read_only: false
options: {}
schema: {}
